name: Deploy Warcraft to server
on: 
    workflow_dispatch:
    push:
     branches:
     - main

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'

    - name: Publish build artifacts
      run: dotnet publish WarcraftPlugin/WarcraftPlugin.csproj --configuration Release --output ./publish

    - name: executing remote ssh commands
      uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SOURCE: "./publish/"
        TARGET: "/home/steam/steamcmd/cs2-ds/game/csgo/addons/counterstrikesharp/plugins/WarcraftPlugin"
        ARGS: "-rlgoDzvc -i"
        SCRIPT_AFTER: |
          sudo chown -R steam:steam /home/steam/steamcmd/
